name: cache

on: 
  workflow_dispatch:

jobs: 
   test-cache:
       name: job to test the cache
       runs-on: ubuntu-latest
       steps: 
          - uses: actions/checkout@4.1.1
          - uses: actions/cache@v4
            id: generateCache
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-

          - run: pip install -r requirements.txt
          - name: confirm cache
            if: steps.generateCache.outputs.cache-hit
            run: echo cache entry found!
          
